/**
 * Autogenerated by Thrift Compiler (0.9.3)
 * <p>
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *
 * @generated
 */
package io.github.bw.example.tutorial;

import java.util.HashMap;
import java.util.Map;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class tutorialConstants {

  public static final int INT32CONSTANT = 9853;

  public static final Map<String, String> MAPCONSTANT = new HashMap<String, String>();

  static {
    MAPCONSTANT.put("hello", "world");
    MAPCONSTANT.put("goodnight", "moon");
  }

}
